@Test
    public void TestAdd () {
        ArrayList NewList1 = new ArrayList();
        Havka dish = new Havka();
        String expResult = dish.name;
        NewList1.add(dish);
        String result = NewList1.get(dish);
        assertEquals(expResult, result); 
    }
    @Test
    public void TestAdd2() throws Exception {
        ArrayList NewList1 = new ArrayList();
        Havka dish = new Havka();
        dish.name = null;
        try {
        NewList1.add(dish);
        if (dish.name==null)throw new Exception();}
        catch (Exception e) {
            System.out.println("Exception 1");
        }               
    }
    @Test
    public void TestAmount () {
        double x = 15.1;
        double sum = 24.0;
        double amount = x+sum;
        double expResult = 39.1;
        String result = String.valueOf(amount);
        assertEquals(expResult, result); 
    }
